using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace Mystpath
{
    /// <summary>
    /// Converts HexGrid simulation data into a visible 3D terrain mesh at runtime.
    ///
    /// Architecture:
    ///   - The HexGrid remains the authoritative source of truth. This class only reads it.
    ///   - The terrain is a single combined mesh. Each hex contributes one center vertex
    ///     (unique to that hex) and six corner vertices that are SHARED with the adjacent
    ///     hexes that meet at the same geometric point.
    ///
    /// Shared vertex topology and smoothing:
    ///   Each flat-top hex corner is shared by exactly three hexes. By using one vertex
    ///   per unique world position (via a position-keyed cache), Unity's RecalculateNormals
    ///   can average the normals of all triangles that meet at each corner across hex
    ///   boundaries, producing smooth normals everywhere instead of per-hex facets.
    ///
    ///   Hex identity is still clearly visible because:
    ///     - Each center vertex retains its cell's pure biome color and exact elevation.
    ///     - Corner heights and colors are averaged over the three contributing cells —
    ///       the same value is computed regardless of which hex "claims" the corner first.
    ///     - Biome color regions are large and distinct at the kingdom scale.
    ///
    /// Corner height/color correctness:
    ///   Corner i of a flat-top hex (at angle 60*i°) is the meeting point of three cells:
    ///   the owning cell, and the neighbors at axial directions (6-i)%6 and (7-i)%6.
    ///   Both the height and the blended color for each corner are averaged over those
    ///   three specific cells. Because every adjacent hex that shares a corner computes
    ///   the same average (same three cells, same formula), the value is identical
    ///   regardless of which hex visits the corner first — the shared vertex is correct.
    ///
    /// Subscribes to WorldGenerator.OnWorldGenerated so terrain rebuilds automatically
    /// whenever the world is regenerated, including R / N debug hotkeys.
    ///
    /// Water representation:
    ///   Water cells are currently rendered as lowered blue terrain — the sea floor
    ///   is a real mesh at a reduced elevation. This is intentional and correct:
    ///   the sea floor should always exist as geometry so coast transitions are clean.
    ///
    ///   A future real water surface layer should:
    ///     - Be a separate GameObject / MeshRenderer sitting above water cells
    ///     - Be generated by a dedicated WaterSurfaceBuilder component (not this class)
    ///     - Read HexCell.IsWater and HexCell.WaterDepth for coverage and tint
    ///     - Use translucency / scroll UVs for visual water motion
    ///     - Not alter this terrain mesh in any way
    ///
    ///   TODO (future): Create WaterSurfaceBuilder that subscribes to OnWorldGenerated
    ///                  and places a flat translucent plane over IsWater regions.
    ///   TODO (future): ShorelineResolver already tags IsShore cells; use those to
    ///                  spawn foam/shoreline edge detail between land and water.
    ///
    /// Does NOT implement prop spawning, building footprints, or final art shading.
    /// </summary>
    public class WorldTerrainBuilder : MonoBehaviour
    {
        // Six axial neighbor directions for flat-top hexes (matches HexCoord._directions).
        // Corner i of a hex is shared with the neighbors at directions i and (i+1) % 6.
        private static readonly HexCoord[] Directions =
        {
            new HexCoord( 1,  0),   // 0 — right
            new HexCoord( 1, -1),   // 1 — upper-right
            new HexCoord( 0, -1),   // 2 — upper-left
            new HexCoord(-1,  0),   // 3 — left
            new HexCoord(-1,  1),   // 4 — lower-left
            new HexCoord( 0,  1),   // 5 — lower-right
        };

        // =====================================================================
        // Inspector Fields
        // =====================================================================

        [Header("References")]
        [Tooltip("Source of hex cell data. Auto-found at runtime if left unassigned.")]
        [SerializeField] private HexGrid _hexGrid;

        [Tooltip("Subscribes to OnWorldGenerated for automatic rebuilds. Auto-found if unassigned.")]
        [SerializeField] private WorldGenerator _worldGenerator;

        [Tooltip("Resolves shore flags before building mesh. Auto-found if unassigned.")]
        [SerializeField] private ShorelineResolver _shorelineResolver;

        [Header("Terrain Settings")]
        [Tooltip("Outer radius of each hex in world units. Must match " +
                 "WorldDebugRenderer._hexWorldSize and HexCoord.ToWorldPosition callers.")]
        [SerializeField] private float _hexSize = 1f;

        [Tooltip("Vertical scale applied to BaseElevation. " +
                 "At 5 an elevation of 1.0 becomes 5 world units above y = 0. " +
                 "Mountain peaks can exceed 1.0 (up to 1.8), so peaks reach ~9 world units " +
                 "while average land (~0.55) sits at ~2.75 — a clear visual hierarchy.")]
        [SerializeField] private float _elevationScale = 5f;

        [Tooltip("Maximum elevation (before scale) used for water cell surfaces. " +
                 "Keeps water visually below all land regardless of raw elevation value.")]
        [SerializeField, Range(0.1f, 0.5f)] private float _waterElevationCap = 0.28f;

        [Header("Material")]
        [Tooltip("Terrain material. If null, created at runtime from Mystpath/TerrainVertexColor. " +
                 "Assign a saved Material asset to avoid runtime shader lookup.")]
        [SerializeField] private Material _terrainMaterial;

        // =====================================================================
        // Public Events & State
        // =====================================================================

        /// <summary>
        /// Fired synchronously at the end of every successful <see cref="BuildTerrain"/> call,
        /// after the mesh and MeshCollider are fully constructed.
        ///
        /// <see cref="WorldPropSpawner"/> subscribes here so it can spawn props on top of
        /// the finished terrain surface. Any system that needs to run AFTER the terrain mesh
        /// exists should subscribe to this event rather than to
        /// <see cref="WorldGenerator.OnWorldGenerated"/>.
        /// </summary>
        public event System.Action OnTerrainBuilt;

        /// <summary>
        /// True after the first successful <see cref="BuildTerrain"/> call.
        /// Systems that subscribe to <see cref="OnTerrainBuilt"/> in their Start() can check
        /// this flag to catch the case where the terrain was already built before they ran.
        /// </summary>
        public bool IsBuilt { get; private set; }

        /// <summary>
        /// The elevation scale currently applied to BaseElevation values.
        /// Exposed so other systems (e.g., WorldPropSpawner) can compute world-space
        /// Y positions from HexCell.BaseElevation without duplicating the constant.
        /// </summary>
        public float ElevationScale => _elevationScale;

        // =====================================================================
        // Private State
        // =====================================================================

        private GameObject _terrainRoot;

        // =====================================================================
        // Unity Lifecycle
        // =====================================================================

        private void Awake()
        {
            // Resolve references only — do not subscribe to events yet.
            // Event subscription happens in Start() so it is guaranteed to occur
            // after all Awake() calls (including GameBootstrap, which fires
            // OnWorldGenerated from within its Awake via GenerateWorld()).
            if (_hexGrid == null)
                _hexGrid = FindFirstObjectByType<HexGrid>();

            if (_worldGenerator == null)
                _worldGenerator = FindFirstObjectByType<WorldGenerator>();

            if (_shorelineResolver == null)
                _shorelineResolver = FindFirstObjectByType<ShorelineResolver>();
        }

        private void Start()
        {
            // Subscribe for future regenerations (debug R / N hotkeys, in-game triggers).
            // ShorelineResolver subscribed in its own Awake(), so it is guaranteed to run
            // before WorldTerrainBuilder's handler when OnWorldGenerated fires — shore flags
            // will always be current before BuildTerrain executes.
            if (_worldGenerator != null)
                _worldGenerator.OnWorldGenerated += HandleWorldGenerated;
            else
                Debug.LogWarning("[WorldTerrainBuilder] WorldGenerator not found. " +
                                 "Terrain will not rebuild automatically on regeneration.");

            // Build immediately using the world data that GameBootstrap.Awake() already
            // generated. The OnWorldGenerated event fired during Awake, before our
            // subscription — this Start() call compensates for that missed event.
            if (_hexGrid != null && _hexGrid.CellCount > 0)
                BuildTerrain();
            else
                Debug.LogWarning("[WorldTerrainBuilder] Grid is empty at Start. " +
                                 "Terrain will build when OnWorldGenerated fires.");
        }

        private void OnDestroy()
        {
            if (_worldGenerator != null)
                _worldGenerator.OnWorldGenerated -= HandleWorldGenerated;
        }

        // =====================================================================
        // Event Handler
        // =====================================================================

        /// <summary>
        /// Invoked by WorldGenerator.OnWorldGenerated after each generation pass.
        /// ShorelineResolver runs first (subscribed earlier) so shore flags are current.
        /// </summary>
        private void HandleWorldGenerated() => BuildTerrain();

        // =====================================================================
        // Public API
        // =====================================================================

        /// <summary>
        /// Builds (or rebuilds) the terrain mesh from the current HexGrid contents.
        /// Previous geometry is destroyed before the new mesh is created.
        /// Safe to call multiple times.
        /// </summary>
        public void BuildTerrain()
        {
            if (_hexGrid == null)
            {
                Debug.LogError("[WorldTerrainBuilder] HexGrid not found. Terrain cannot be built.");
                return;
            }

            // Ensure shore flags are current. ShorelineResolver may already have run via
            // its own OnWorldGenerated subscription, but calling it here is idempotent.
            _shorelineResolver?.ResolveShorelineCells();

            if (_terrainRoot != null)
                Destroy(_terrainRoot);

            _terrainRoot = new GameObject("TerrainRoot");
            _terrainRoot.transform.SetParent(transform, worldPositionStays: false);

            EnsureMaterial();
            BuildCombinedMesh();

            IsBuilt = true;

            Debug.Log("[WorldTerrainBuilder] Terrain mesh built successfully.");

            // Notify subscribers (WorldPropSpawner, etc.) that the terrain surface
            // and its MeshCollider are ready. Fired after IsBuilt is set to true so
            // systems that check IsBuilt in Start() see the correct state.
            OnTerrainBuilt?.Invoke();
        }

        // =====================================================================
        // Material
        // =====================================================================

        private void EnsureMaterial()
        {
            if (_terrainMaterial != null) return;

            Shader shader = Shader.Find("Mystpath/TerrainVertexColor");

            if (shader == null)
            {
                Debug.LogWarning("[WorldTerrainBuilder] Shader 'Mystpath/TerrainVertexColor' not " +
                                 "found. Falling back to Universal Render Pipeline/Particles/Unlit.");
                shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
            }

            if (shader == null)
            {
                Debug.LogWarning("[WorldTerrainBuilder] Fallback shader also not found. " +
                                 "Using Universal Render Pipeline/Lit.");
                shader = Shader.Find("Universal Render Pipeline/Lit");
            }

            _terrainMaterial = new Material(shader) { name = "TerrainMaterial_Runtime" };
        }

        // =====================================================================
        // Mesh Generation
        // =====================================================================

        /// <summary>
        /// Builds a single combined terrain mesh for the entire HexGrid.
        ///
        /// Vertex layout:
        ///   Each hex contributes one unique center vertex. The six corner vertices at each
        ///   hex corner are shared with the adjacent hexes that touch the same geometric point.
        ///   A position-keyed dictionary (CornerKey) ensures each unique world position
        ///   creates exactly one vertex, regardless of which hex processes it first.
        ///
        /// Smoothing:
        ///   Because corner vertices are shared, Unity's RecalculateNormals averages the
        ///   normals of every triangle that meets at each corner — producing smooth surface
        ///   normals across hex boundaries rather than per-hex facets.
        ///   Center vertices are still unique, so the hex-plateau gradient is preserved.
        ///
        /// Correctness:
        ///   Corner height and color are averaged over the same three cells regardless of
        ///   which hex claims the vertex first, so the value is deterministic and correct.
        /// </summary>
        private void BuildCombinedMesh()
        {
            var vertices  = new List<Vector3>();
            var colors    = new List<Color>();
            var uvs       = new List<Vector2>(); // UV0: (BaseElevation, IsShore) for shader effects
            var triangles = new List<int>();

            // Maps a quantized world-position key to an already-created vertex index.
            // Corner vertices at the same geometric position share one entry in this cache.
            var cornerCache = new Dictionary<long, int>(capacity: _hexGrid.CellCount * 3);

            foreach (HexCell cell in _hexGrid.GetAllCells())
            {
                Vector3 worldXZ   = cell.Coord.ToWorldPosition(_hexSize);
                float   centerY   = CellHeight(cell);
                Color   cellColor = BiomeBlendCalculator.GetCellColor(cell);

                // Center vertex: unique per hex, carries the cell's pure biome color
                // and UV0 data (elevation, IsShore) for the terrain shader.
                int centerIdx = vertices.Count;
                vertices.Add(new Vector3(worldXZ.x, centerY, worldXZ.z));
                colors.Add(cellColor);
                uvs.Add(BiomeBlendCalculator.GetCellUV(cell));

                // Six corner vertices — shared with whichever neighboring hex visits
                // the same geometric corner position first.
                int[] cornerIdx = new int[6];
                for (int i = 0; i < 6; i++)
                {
                    float rad = i * 60f * Mathf.Deg2Rad;
                    float wx  = worldXZ.x + Mathf.Cos(rad) * _hexSize;
                    float wz  = worldXZ.z + Mathf.Sin(rad) * _hexSize;
                    long  key = CornerKey(wx, wz);

                    if (!cornerCache.TryGetValue(key, out int idx))
                    {
                        // First hex to reach this corner — compute and store the vertex.
                        HexCell n1 = NeighborOrNull(cell.Coord, (6 - i) % 6);
                        HexCell n2 = NeighborOrNull(cell.Coord, (7 - i) % 6);

                        idx = vertices.Count;
                        vertices.Add(new Vector3(wx, CornerHeight(cell, i), wz));
                        colors.Add(BiomeBlendCalculator.BlendCornerColor(cell, n1, n2));
                        uvs.Add(BiomeBlendCalculator.BlendCornerUV(cell, n1, n2));
                        cornerCache[key] = idx;
                    }

                    cornerIdx[i] = idx;
                }

                // Six triangles with CW winding viewed from +Y (front face = +Y normal).
                for (int i = 0; i < 6; i++)
                {
                    triangles.Add(centerIdx);              // cell center
                    triangles.Add(cornerIdx[(i + 1) % 6]); // next corner
                    triangles.Add(cornerIdx[i]);            // current corner
                }
            }

            var mesh = new Mesh { name = "TerrainCombined" };

            // Shared corner vertices reduce total count to roughly 1 center + 2 unique corners
            // per hex on average (each corner shared by 3 hexes). A 96×96 grid produces
            // ~28 000 verts — well within 16-bit range. The check is kept for safety.
            mesh.indexFormat = vertices.Count > 65535 ? IndexFormat.UInt32 : IndexFormat.UInt16;

            mesh.SetVertices(vertices);
            mesh.SetColors(colors);
            mesh.SetUVs(0, uvs);       // UV0: .x = BaseElevation, .y = IsShore flag
            mesh.SetTriangles(triangles, 0);

            // Shared corner vertices allow RecalculateNormals to average across hex
            // boundaries, producing smooth normals everywhere on the terrain surface.
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();

            var go = new GameObject("TerrainChunk_0");
            go.transform.SetParent(_terrainRoot.transform, worldPositionStays: false);
            go.AddComponent<MeshFilter>().sharedMesh       = mesh;
            go.AddComponent<MeshRenderer>().sharedMaterial = _terrainMaterial;

            // MeshCollider enables Physics.Raycast hits on the terrain surface.
            // Used by WorldPropSpawner (future: for precise per-position Y sampling),
            // and by future click-to-select, click-to-build, and NPC pathfinding systems.
            // Non-convex, non-trigger — correct for walkable/clickable terrain.
            go.AddComponent<MeshCollider>().sharedMesh = mesh;
        }

        /// <summary>
        /// Returns a stable long key for a world-space corner position.
        /// Rounds to 3 decimal places — sufficient to uniquely distinguish all hex corner
        /// positions for any hex size ≥ 0.01. A fixed offset is added before packing so
        /// small negative coordinates (possible at the grid boundary) remain non-negative.
        /// </summary>
        private static long CornerKey(float x, float z)
        {
            // With hexSize = 1 and a 96-hex grid:
            //   max x ≈ 144, max z ≈ 166; min x/z ≈ −1 (one hex-size border corner).
            //   At 1000× precision: xi/zi up to ~167 000.  offset = 10 000 is safe.
            //   Multiplier 500 000 > max zi, so xi * 500 000 + zi has no collisions.
            const long offset     = 10_000L;
            const long multiplier = 500_000L;
            long xi = (long)Mathf.Round(x * 1000f) + offset;
            long zi = (long)Mathf.Round(z * 1000f) + offset;
            return xi * multiplier + zi;
        }

        // =====================================================================
        // Height Helpers
        // =====================================================================

        /// <summary>
        /// World-space Y height for a cell's center vertex.
        /// Water cells are capped at <see cref="_waterElevationCap"/> so they always sit
        /// visually below adjacent land cells. This models the sea floor — the terrain
        /// mesh is the floor of the ocean; a future water surface layer will sit above it.
        /// </summary>
        private float CellHeight(HexCell cell)
        {
            float elev = cell.IsWater
                ? Mathf.Min(cell.BaseElevation, _waterElevationCap)
                : cell.BaseElevation;
            return elev * _elevationScale;
        }

        /// <summary>
        /// World-space Y height for corner <paramref name="cornerIndex"/> of
        /// <paramref name="cell"/>. Corner i is the meeting point of the owning cell
        /// and the neighbors at axial directions (6-i)%6 and (7-i)%6. The average of
        /// those three heights is the value stored in the shared corner vertex — identical
        /// regardless of which of the three hexes computes it first.
        /// </summary>
        private float CornerHeight(HexCell cell, int cornerIndex)
        {
            float h0 = CellHeight(cell);

            HexCell n1 = NeighborOrNull(cell.Coord, (6 - cornerIndex) % 6);
            HexCell n2 = NeighborOrNull(cell.Coord, (7 - cornerIndex) % 6);

            float h1 = n1 != null ? CellHeight(n1) : h0;
            float h2 = n2 != null ? CellHeight(n2) : h0;

            return (h0 + h1 + h2) / 3f;
        }

        /// <summary>
        /// Returns the grid cell at the neighbor in direction <paramref name="dirIndex"/>
        /// from <paramref name="origin"/>, or null if that coordinate is outside the grid.
        /// </summary>
        private HexCell NeighborOrNull(HexCoord origin, int dirIndex)
        {
            _hexGrid.TryGetCell(origin + Directions[dirIndex], out HexCell cell);
            return cell;
        }
    }
}
