namespace Mystpath
{
    /// <summary>
    /// Manages the movement of resources between storage locations in the kingdom.
    /// Haul tasks are generated by the KingdomScheduler and executed step-by-step
    /// by NPC carriers: pick up from source, travel, deliver to destination.
    /// </summary>
    public class HaulingSystem
    {
        /// <summary>
        /// Called when an NPC completes a haul step (pick-up or drop-off).
        /// Transfers resources between source and destination InventoryStores.
        /// </summary>
        /// <param name="haulTask">The active haul TaskInstance being executed.</param>
        /// <param name="carrier">The NPC performing the haul.</param>
        /// <param name="source">The store resources are taken from.</param>
        /// <param name="destination">The store resources are delivered to.</param>
        public void ProcessHaulStep(TaskInstance haulTask, NpcEntity carrier, InventoryStore source, InventoryStore destination)
        {
            // TODO: Validate task type is TaskType.Haul
            // TODO: Calculate carry capacity from carrier.Stats.Strength
            // TODO: On pick-up step: Remove from source, note carried amount
            // TODO: On delivery step: Add carried amount to destination
            // TODO: Record the transfer in the kingdom's ResourceLedger
        }
    }
}
